# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306204394fc565e71980223a52893384917e3e802045294a58f0e5c904bad71a2f161261ed25cadb32abd535cc3e9b15456176eb44cb78c66b56805a6772cc41

test:
  secret_key_base: 56fa8d4bf6bf24c0156745ba763b846f5cdcf10f4890c67fd719856f1a3c82239f2c9010e0df7178f9256bcc52360acd89f435e0ece76745e5995f4c8192d5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
